services:
  - type: web
    name: git-swe-agent
    env: node
    plan: starter
    buildCommand: npm ci && npm run build
    startCommand: npm start
    healthCheckPath: /
    runtime: node
    autoDeploy: false
    envVars:
      - key: NODE_ENV
        value: production
      - key: APP_ID
        sync: false
      - key: PRIVATE_KEY
        sync: false
      - key: WEBHOOK_SECRET
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: PORT
        value: 3000